# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 18:55
from __future__ import unicode_literals

from django.db import migrations

from openedx.core.djangoapps.password_policy.constants import PASSWORD_POLICY_COMPLIANT_USERS_GROUP_NAME


def up(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name=PASSWORD_POLICY_COMPLIANT_USERS_GROUP_NAME)


def down(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name=PASSWORD_POLICY_COMPLIANT_USERS_GROUP_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0008_alter_user_username_max_length')
    ]

    operations = [
        migrations.RunPython(up, down)
    ]


